import { UseCaseState } from "./types";

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .substring(0, 60);
}

export function generateTurtle(s: UseCaseState): string {
  const base = "https://educore.org";
  const ucSlug = slugify(s.title || "unnamed");
  const ucUri = `${base}/usecase/${ucSlug}`;

  const lines: string[] = [
    `@prefix uc:     <${base}/ontology/> .`,
    `@prefix schema: <https://schema.org/> .`,
    `@prefix skos:   <http://www.w3.org/2004/02/skos/core#> .`,
    `@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .`,
    `@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .`,
    `@prefix xsd:    <http://www.w3.org/2001/XMLSchema#> .`,
    `@prefix ceds:   <https://ceds.ed.gov/element/> .`,
    ``,
    `# ─────────────────────────────────────────────`,
    `# Use Case: ${s.title || "Untitled"}`,
    `# Generated by EDUcore Use Case Registry`,
    `# ─────────────────────────────────────────────`,
    ``,
    `<${ucUri}> a uc:UseCase ;`,
    `    rdfs:label "${escTurtle(s.title)}"@en ;`,
  ];

  if (s.topic) {
    const topicSlug = slugify(s.topic);
    lines.push(`    uc:topic <${base}/topic/${topicSlug}> ;`);
  }

  if (s.businessDriver) {
    lines.push(`    uc:businessDriver "${escTurtle(s.businessDriver)}"@en ;`);
  }

  if (s.intro) {
    lines.push(`    schema:description "${escTurtle(s.intro)}"@en ;`);
  }

  if (s.primaryCategory) {
    lines.push(`    schema:category "${escTurtle(s.primaryCategory)}"@en ;`);
  }

  s.tags.forEach((tag) => {
    lines.push(`    schema:keywords "${escTurtle(tag)}"@en ;`);
  });

  // Actors
  s.actors.forEach((actor, i) => {
    const aSlug = slugify(actor.name || `actor-${i}`);
    lines.push(`    uc:hasActor <${ucUri}/actor/${aSlug}> ;`);
  });

  // User Stories
  s.userStories.forEach((us) => {
    const usSlug = slugify(us.id || `us-${us.actor}`);
    lines.push(`    uc:hasUserStory <${ucUri}/story/${usSlug}> ;`);
  });

  // Steps
  s.steps.forEach((_, i) => {
    lines.push(`    uc:hasStep <${ucUri}/step/${i + 1}> ;`);
  });

  // Close use case block
  if (lines[lines.length - 1].endsWith(";")) {
    lines[lines.length - 1] = lines[lines.length - 1].replace(/;$/, ".");
  }

  // Topic block
  if (s.topic) {
    const topicSlug = slugify(s.topic);
    lines.push(``);
    lines.push(`<${base}/topic/${topicSlug}> a uc:Topic ;`);
    lines.push(`    rdfs:label "${escTurtle(s.topic)}"@en .`);
  }

  // Actor blocks
  s.actors.forEach((actor, i) => {
    const aSlug = slugify(actor.name || `actor-${i}`);
    lines.push(``);
    lines.push(`<${ucUri}/actor/${aSlug}> a uc:Actor ;`);
    lines.push(`    rdfs:label "${escTurtle(actor.name)}"@en ;`);
    if (actor.desc) {
      lines.push(`    schema:description "${escTurtle(actor.desc)}"@en ;`);
    }
    lines.push(`    uc:participatesIn <${ucUri}> .`);
  });

  // Step blocks
  s.steps.forEach((step, i) => {
    const actorName = s.actors[step.actorIdx]?.name ?? "";
    const actorSlug = slugify(actorName || `actor-${step.actorIdx}`);
    lines.push(``);
    lines.push(`<${ucUri}/step/${i + 1}> a uc:ProcessStep ;`);
    lines.push(`    uc:stepNumber ${i + 1} ;`);
    if (step.action) {
      lines.push(`    uc:action "${escTurtle(step.action)}"@en ;`);
    }
    if (step.dataIn) {
      lines.push(`    uc:dataInput "${escTurtle(step.dataIn)}"@en ;`);
    }
    if (step.dataOut) {
      lines.push(`    uc:dataOutput "${escTurtle(step.dataOut)}"@en ;`);
    }
    if (step.logic) {
      lines.push(`    uc:transformationLogic "${escTurtle(step.logic)}"@en ;`);
    }
    if (actorName) {
      lines.push(`    uc:performedBy <${ucUri}/actor/${actorSlug}> ;`);
    }
    lines.push(`    uc:partOf <${ucUri}> .`);
  });

  // User Story blocks
  s.userStories.forEach((us) => {
    const usSlug = slugify(us.id || `us-${us.actor}`);
    lines.push(``);
    lines.push(`<${ucUri}/story/${usSlug}> a uc:UserStory ;`);
    if (us.id) lines.push(`    uc:storyId "${escTurtle(us.id)}"@en ;`);
    if (us.actor) lines.push(`    uc:actor "${escTurtle(us.actor)}"@en ;`);
    if (us.action) lines.push(`    uc:action "${escTurtle(us.action)}"@en ;`);
    if (us.dataImplications) lines.push(`    uc:dataImplications "${escTurtle(us.dataImplications)}"@en ;`);
    if (us.acceptanceCriteria) lines.push(`    uc:acceptanceCriteria "${escTurtle(us.acceptanceCriteria)}"@en ;`);
    lines.push(`    uc:partOf <${ucUri}> .`);
  });

  // Data Element blocks
  s.dataElements.forEach((de, i) => {
    const deSlug = slugify(de.name || `data-${i}`);
    lines.push(``);
    lines.push(`<${ucUri}/data/${deSlug}> a uc:DataElement ;`);
    lines.push(`    rdfs:label "${escTurtle(de.name)}"@en ;`);
    if (de.def) lines.push(`    schema:description "${escTurtle(de.def)}"@en ;`);
    if (de.url) lines.push(`    schema:url <${de.url}> ;`);
    lines.push(`    uc:usedIn <${ucUri}> .`);
  });

  // Standards mappings
  s.standardsMappings.forEach((m, i) => {
    lines.push(``);
    lines.push(`<${ucUri}/mapping/${i + 1}> a uc:StandardsMapping ;`);
    if (m.dataElement) lines.push(`    uc:sourceElement "${escTurtle(m.dataElement)}"@en ;`);
    if (m.standard) lines.push(`    uc:targetStandard "${escTurtle(m.standard)}"@en ;`);
    if (m.mappedField) lines.push(`    uc:targetField "${escTurtle(m.mappedField)}"@en ;`);
    if (m.mappingNotes) lines.push(`    skos:note "${escTurtle(m.mappingNotes)}"@en ;`);
    lines.push(`    uc:partOf <${ucUri}> .`);
  });

  return lines.join("\n");
}

export function generateJSONLD(s: UseCaseState): string {
  const base = "https://educore.org";
  const ucSlug = slugify(s.title || "unnamed");

  const doc: Record<string, unknown> = {
    "@context": {
      "@vocab": `${base}/ontology/`,
      schema: "https://schema.org/",
      rdfs: "http://www.w3.org/2000/01/rdf-schema#",
      skos: "http://www.w3.org/2004/02/skos/core#",
    },
    "@id": `${base}/usecase/${ucSlug}`,
    "@type": "UseCase",
    "rdfs:label": s.title,
    topic: s.topic || undefined,
    businessDriver: s.businessDriver || undefined,
    "schema:description": s.intro || undefined,
    "schema:category": s.primaryCategory || undefined,
    "schema:keywords": s.tags.length > 0 ? s.tags : undefined,
    hasActor: s.actors.map((a) => ({
      "@type": "Actor",
      "rdfs:label": a.name,
      "schema:description": a.desc || undefined,
    })),
    hasStep: s.steps.map((st, i) => ({
      "@type": "ProcessStep",
      stepNumber: i + 1,
      action: st.action,
      dataInput: st.dataIn || undefined,
      dataOutput: st.dataOut || undefined,
      transformationLogic: st.logic || undefined,
      performedBy: s.actors[st.actorIdx]?.name,
    })),
    hasUserStory:
      s.userStories.length > 0
        ? s.userStories.map((us) => ({
            "@type": "UserStory",
            storyId: us.id,
            actor: us.actor,
            action: us.action,
            dataImplications: us.dataImplications,
            acceptanceCriteria: us.acceptanceCriteria,
          }))
        : undefined,
    standardsMapping:
      s.standardsMappings.length > 0
        ? s.standardsMappings.map((m) => ({
            "@type": "StandardsMapping",
            sourceElement: m.dataElement,
            targetStandard: m.standard,
            targetField: m.mappedField,
            "skos:note": m.mappingNotes,
          }))
        : undefined,
  };

  // Remove undefined values
  const clean = (obj: unknown): unknown => {
    if (Array.isArray(obj)) return obj.map(clean);
    if (obj && typeof obj === "object") {
      return Object.fromEntries(
        Object.entries(obj as Record<string, unknown>)
          .filter(([, v]) => v !== undefined)
          .map(([k, v]) => [k, clean(v)])
      );
    }
    return obj;
  };

  return JSON.stringify(clean(doc), null, 2);
}

function escTurtle(s: string): string {
  return (s || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}
